### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [TatianaGradinar/grid-template-course-project#1]
1)
подобные замечания можно исправить
![image](https://user-images.githubusercontent.com/8464662/175758449-588a7be5-f04a-4afd-8951-44303318610e.png)

2)

В HTML5 нет такого синтаксиса, вы используете синтаксис XHTML, что противоречит инструкции DOCTYPE html.
Разберитесь в причине появление такого синтаксиса. Обычно виновником является плагин PRETTIER, неправильно установленный в качестве форматтера по умолчанию для HTML-страниц. 
С деталями вы можете ознакомиться в уроке по настройке VSCode.
Затем приведите разметку всех без исключения файлов вашего проекта к стандарту HTML5, удалив обратные слеши для всех непарных тегов.
После этого выполните автоформатирование кода для всех исправленных файлов.

![image](https://user-images.githubusercontent.com/8464662/175758459-6846e237-6258-4cc4-b8ad-0d2274685b7d.png)

3)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/175758474-02ea54c9-e6c3-4749-a777-acce66d024fe.png)

4)
в данном случае переделывать не нужно, баллы за это не снижал.
но в целом - отступление от макета является грубейшей ошибкой
![image](https://user-images.githubusercontent.com/8464662/175758515-8d1ca99e-d203-4cbc-b37d-ff70ad35bda3.png)

**Comment by TatianaGradinar** [comment]
Здравствуйте, я исправила ошибки. Спасибо и хорошего вечера!

https://github.com/TatianaGradinar/grid-template-course-project

https://tatianagradinar.github.io/grid-template-course-project/


сб, 25 июн. 2022 г. в 07:53, Andrey ***@***.***>:
